### ISSUE TITLE
Can't get started

### ISSUE THREAD

**Issue by GregDevine** [sorenkrabbe/Chrome-Salesforce-inspector#116]
Have installed Salesforce Inspector - excited about using it.  But don't see the icon.  Do I have to do anything other than install the extension. - I am not a  developer - The site I am testing on has a custom domain.

**Comment by jesperkristensen** [comment]
Hi. The little blue button should appear at the right side of the window when the extension is installed and you are logged in to Salesforce.

Here are some questions that could help me figure out what is wrong:
Which browser and which version of it are you using?
If you open the F12 console, which messages does it print?
Have you seen [the troubleshooting information](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector#troubleshooting)?

**Comment by jesperkristensen** [comment]
No answer, closing.
