### ISSUE TITLE
additional matching URL cloudforce.com

### ISSUE THREAD

**Issue by ryanphillips-ncino** [sorenkrabbe/Chrome-Salesforce-inspector#118]
please add `https://*.cloudforce.com/*` to the matched URLs. Salesforce uses that in certain demo orgs

**Comment by AnzeKovac** [comment]
This would be awesome !

**Comment by franmico** [comment]
we have created an app and we are ISV Partners. When we create orgs from our ISV Org the domain gets prefix with the name of the company so all our org for all our clients have a different domain than the standard ones. Would be awesome to get this fixed as it is such a great tool that will save us a lot of time :) Thank you for creating this!

**Comment by jesperkristensen** [comment]
How can I make my org use that domain so I can test this?
