### ISSUE TITLE
Error retrieving record: UNKNOWN_EXCEPTION - ErrorId: 784809428-16121 (1786437354)

### ISSUE THREAD

**Issue by hwong103** [sorenkrabbe/Chrome-Salesforce-inspector#120]
Hi

We use this Chrome Extension a lot and have found it extremely useful and dependent on it. Recently we've started to get this error code on the Opportunity object but it doesn't appear to happen on any other object. We've just gone live with a project based around Opportunities and transactions so quite a bit of change has happened in this space.

Initially I thought it might be due to my redirect but taking it off still comes up with this error. If you can let me know what we've changed to cause this error that would be awesome.

Thanks!

**Comment by sorenkrabbe** [comment]
It’s an internal salesforce error returned when the salesforce inspector calls the standard salesforce apis.
It’s likely specific to your org. Your best chance is to contact salesforce support with the error ID

Good luck
