### ISSUE TITLE
Firefox 57 (64 bit) errors

### ISSUE THREAD

**Issue by all2human** [sorenkrabbe/Chrome-Salesforce-inspector#122]
The export button now has the following error "Network error, offline or timeout".  Metadata cannot be loaded.  

Show All Data returns the following errors "Error describing global: Network error, offline or timeout
Error describing object: Network error, offline or timeout
Error retrieving record: Network error, offline or timeout
Error querying tooling particles: Network error, offline or timeout"

**Comment by AntunBartonicek** [comment]
This seems to be related to Tracking protection.
If you turn it off then everything starts working again.

**Comment by all2human** [comment]
Yes that worked.

**Comment by segdan** [comment]
I'm having the same issue, but disable tracking protection doesn't seem to work...am I missing something..?
