### ISSUE TITLE
cloudforce.com not supported, Salesforce menu inspector doesn't appear

### ISSUE THREAD

**Issue by kalius** [sorenkrabbe/Chrome-Salesforce-inspector#129]
Hi,

first I have to thank you, since this is daily used plugin. It saves a lot of time!

Is it possible to support cloudforce.com domain as well? This is domain used for trialforce SF projects.
Example:
![image](https://user-images.githubusercontent.com/786783/40307839-58c28e24-5d04-11e8-969e-fb824873501e.png)

**Comment by PavelCZE** [comment]
Duplicate of #118
