### ISSUE TITLE
Salesforce My Domain breaks Inspector

### ISSUE THREAD

**Issue by cehunter** [sorenkrabbe/Chrome-Salesforce-inspector#132]
It appears once you enable My Domain in Salesforce which is needed for much of the lighting functionality you lose the ability to use the inspector tool.  You no longer have the show all data option available, in addition when you query it gives you the invalid session error.  

Love this tool its been super helpful!!!

**Comment by sorenkrabbe** [comment]
The tool works fine for many users with Salesforce My Domain enabled. Almost all features (incl. the ones you mention) do support Lightning Experience.
I therefore close this issue and suggest you to create another one with more detail on your setup and what you experience, if you still experience the issue.

**Comment by cehunter** [comment]
Hmm interesting, thank you! I will dig deeper and see what else could be causing this it worked amazing right up until we enabled myDomain.  Appreciate the quick response!!

**Comment by colinkenworthy** [comment]
I also had no 'Show All Data' button.  I was on a MyDomain org that used to be on EU2 but moved to UM2.
In the readme documentation, under Troubleshooting, it mentions deleting "sid" cookie data.
If you don't mind deleting all your cookies this is a quick way to fix it. Settings > Advanced > Clear browsing Data.
But you can just delete the cookies you need, Settings > Advanced > Content Setting > Cookies > See All Cookies.  I searched for and deleted all EU2, UM2, *MyCompanyDomainName*.  When I restarted Chrome my 'Show All Data' was there.
