### ISSUE TITLE
Chrome: INVALID_SESSION_ID

### ISSUE THREAD

**Issue by bramirez37** [sorenkrabbe/Chrome-Salesforce-inspector#135]
I can't import or export the data from my clients org. either it says 
"Error describing global: INVALID_SESSION_ID: Session expired or invalid
Error describing object: INVALID_SESSION_ID: Session expired or invalid
Error querying tooling particles: INVALID_SESSION_ID: Session expired or invalid"

or 

"Loading metadata failed. Retry"

But i am connected. Please help

**Comment by bramirez37** [comment]
Hi guys, can someone help me? I am quite desperate for I grown used to it and now I can't use it anymore. HELP

**Comment by raphabarreiros** [comment]
> Hi guys, can someone help me? I am quite desperate for I grown used to it and now I can't use it anymore. HELP

Just clean your browser's cookies and it will work

**Comment by bramirez37** [comment]
Yeah I did and it worked. Thanks!!!

> > Hi guys, can someone help me? I am quite desperate for I grown used to it and now I can't use it anymore. HELP
> 
> Just clean your browser's cookies, logout from your org, login and try again. It will work
