### ISSUE TITLE
Selecting a saved queries returns an error

### ISSUE THREAD

**Issue by rrgripp** [sorenkrabbe/Chrome-Salesforce-inspector#136]
When selecting a saved query, the query input field is replaced with
```[object Object]```

instead of the selected query

**Comment by HartmannTim** [comment]
Would be pleased if this get fixed soon.

**Comment by AziEI** [comment]
Is it still an issue? Cannot replicate it anymore.

**Comment by jesperkristensen** [comment]
Fixed, thanks @EvAzi
