### ISSUE TITLE
maximum export size

### ISSUE THREAD

**Issue by pfmd86** [sorenkrabbe/Chrome-Salesforce-inspector#142]
What is the limit for an export? I try to export 9 million datasets (just the ID and one field). Chromes crashed after 4 Million. I guess this is either related to RAM or Chrome can't create so many table rows to show the result? Any experiences?

**Comment by jesperkristensen** [comment]
We only create the table rows that are visible as you scroll. So no matter how much data you export, there should never exist more than a few hundred rows in the table. It is most likely related to the RAM needed to hold the data. Browsers typically limit each tab to something considerably lower than what is available in the machine to make sure one tab cannot take the whole RAM.
