### ISSUE TITLE
Additional matching URL visualforce.com

### ISSUE THREAD

**Issue by hohsy654** [sorenkrabbe/Chrome-Salesforce-inspector#143]
Hi, Salesforce are changing their URL format for Visualforce page. Can we please add visualforce.com to the matched URLs? Thanks.

Reference: https://help.salesforce.com/articleView?id=000312748&language=en_US&type=1

```
- Old URL format: https://<MyDomain>--c.<instance>.visual.force.com/apex/<pagename>
- New URL format: https://<MyDomain>--c.visualforce.com/apex/<pagename>
```

**Comment by hugocharbonneau** [comment]
Hi. I am not able to use the extension from a Sandbox on custom VF pages since the URL is visualforce.com
