### ISSUE TITLE
Select ALL (*) not working

### ISSUE THREAD

**Issue by machond** [sorenkrabbe/Chrome-Salesforce-inspector#144]
Hi,
Why SELECT * FROM xxxxyyyzzz not work? How Select all columns with records from certain table?

Regards, M.

**Comment by jesperkristensen** [comment]
You select all by typing "select  from xxxxyyyzzz", then place the cursor between "select" and "from" and then press Ctrl+Space to autocomplete all fields.

The * syntax is not supported by Salesforce and is not something the inspector should try to change. I am open for ways to make the autocomplete more discovereable.
