### ISSUE TITLE
Site Access for Custom URLs

### ISSUE THREAD

**Issue by sdchi** [sorenkrabbe/Chrome-Salesforce-inspector#148]
Will you be able to support giving an option to add custom URLs to Site Access? 

Currently the extension is scoped to 3 sites (https://*.cloudforce.com/*, https://*.force.com/*, https://*.salesforce.com/*). One of our org Salesforce apps is proxied and its URL is changed from "https://*.force.com/*" to "https://*.force.com.*"; therefore, Salesforce Inspector does not work for this app. Adding ability to add a custom URL to Site Access will allow to scope the extension to any domain. 

Alternatively, would it be possible to change the currently scoped sites to be without the last slash in the URLs? (for example: "https://*.force.com*" vs. "https://*.force.com/*", so the extension would be scoped to https://*.cloudforce.com*, https://*.force.com*, https://*.salesforce.com*)

**Comment by jesperkristensen** [comment]
Sorry, but the URL matching does not work that way (see https://developer.chrome.com/extensions/match_patterns)

It looks like the only thing that would work in your case would be to run the inspector on all hosts, which I don't want to do for security, privacy and user trust reasons. The world is full of apps that request suspicious permissions, and I don't want the inspector to be one of them. Besides it increases the risk of the extension being banned from browser's extension stores.

Maybe there is a different solution if you can describe the proxy setup in a bit more detail.

This request looks a bit like #121. If it is the same setup here, that is another reason for not fixing it.

The best advice I can give you is to fix your proxy setup, and alternatively you can fork this extension and maintain your own "Salesforce inspector for {insert proxy name here}".
