### ISSUE TITLE
Show field metadata missing after update

### ISSUE THREAD

**Issue by bbondwvu** [sorenkrabbe/Chrome-Salesforce-inspector#150]
After updating to the lastest version 1.8, the show field metadata button no longer shows/exists.

![Account__Jump_Consulting___Salesforce_-_Performance_Edition](https://user-images.githubusercontent.com/5446578/70077351-a130d600-15ce-11ea-9939-a79b749217a2.png)

**Comment by Abbiees** [comment]
Did the new update v1.8 remove the option of **show field metadata** from Salesforce Inspector?

**Comment by sorenkrabbe** [comment]
Not intentionally. It will be back in the next release. But still supports Classic only.

**Comment by Abbiees** [comment]
Thank you for the information, but it's not showing as an option on Classic in my Orgs. 

![image](https://user-images.githubusercontent.com/58525339/70168416-10b5cc80-1686-11ea-890e-121827d8e4af.png)

**Comment by sorenkrabbe** [comment]
Right. It was unintentionally hidden in 1.8 and will be back in 1.9. This issue is marked closed because a fix has been committed to source. It just hasn’t yet been released to chrome/Firefox

**Comment by Abbiees** [comment]
Ok, Thank you.
