### ISSUE TITLE
Rest Explorer not working 'sfConn is not defined'

### ISSUE THREAD

**Issue by mnunezdm** [sorenkrabbe/Chrome-Salesforce-inspector#152]
Hi!

Im trying to invoke some salesforce web services with the rest explorer but its not working, I get a sfConn is not defined error when executing in the developer tools

I'm currently trying in an scratch org but I am also trying in standard sandbox

![image](https://user-images.githubusercontent.com/10410852/70543469-b8416c00-1b6a-11ea-82e6-b3adaba03c16.png)

**Comment by chexxor** [comment]
Looks like `sfConn` is no longer a global variable, which was caused by the change to ES Modules here:

https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/commit/530e056191df7073f21855af9619ece8ea701855#diff-01e0fe59e9e6c08eb65687f273452ee6

Offhand, I don't have a clear solution to this -- any ideas on how to fix this?

- Do we need to make these global?
- Is there a "better" option?

**Comment by jefersonchaves** [comment]
I guess we could make it global similar to `display` (see this [code](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/blob/530e056191df7073f21855af9619ece8ea701855/addon/explore-api.js#L329)).

If I put this together, is this something you could help out @chexxor?

**Comment by jefersonchaves** [comment]
The workaround I have found in Google chrome was to use dynamic import (copy the URL from `inspector.js` - maybe that is something that can be printed out):
```
import('chrome-extension://aodjmnfhjibkcdimpodiifdjnnncaafh/inspector.js').then(m => module = m);
```

Then reference the loaded module in the examples (see the `module.sfConn` instead of `sfConn`):
```
display(module.sfConn.rest("/services/data/v48.0/query/?q=" + encodeURIComponent("select Id, Name from Account where CreatedDate = LAST_WEEK")));
```

**Comment by chexxor** [comment]
@jefersonchaves Yeah, I can try to help out. I've not built this project before, but I'll give it a try if you let me know how I could help.
