### ISSUE TITLE
Block Salesforce Inspector for non Admins

### ISSUE THREAD

**Issue by patrykzak** [sorenkrabbe/Chrome-Salesforce-inspector#159]
I need to make sure users cannot import and export data in bulk, is there any way to block Salesforce Inspector other than:
a) uncheck API enabled permission
b) Transaction security policy which only will block exports

I can easily block workbench and dataloader from connected app manager, but I am concerned about security while using Salesforce Inspector, it's an awesome tool, never though I will need to block this for non admin users. Any ideas kindly appreciated.

**Comment by sorenkrabbe** [comment]
You could enable the [API whitelisting](https://help.salesforce.com/articleView?id=security_api_access_control_all_users.htm&type=5) feature.

Currently the inspector uses the same session as the browser. The browser session will no longer allow API access.

When issue #149 gets resolved you'll also be able to whitelist the inspector for selected groups of users.

I'll close with this comment as no work needs to be done.

**Comment by YuriGarcia** [comment]
Hello @sorenkrabbe, could you please elaborate a lit bit on this approach? Should we create a new connected app? Thanks.
