### ISSUE TITLE
Lost session connection in new release

### ISSUE THREAD

**Issue by ccusic** [sorenkrabbe/Chrome-Salesforce-inspector#168]
This week one of my team members and I noticed that Salesforce Inspector is no longer able to connect to our logged in instance. When logging into Prod or even other Sandboxes, we are able to connect successfully. The issue could be Sandbox specific, however last week I was able to connect to this Sandbox successfully, so I'm not sure what setting could've changed to block access. This makes me think that something from a recent Salesforce release (applied only to this Sandbox) could've broken the integration. 

I've used Salesforce Inspector for years and have often recommended it to my global team as my top Salesforce productivity feature, so losing access to my connection is currently a massive productivity drain as I've found no other comparable tool.

In my screenshots, I had just logged back in and refreshed the page to reload my connection, so my session should be active, but not able to connect to the Metadata API nor see the See All Data button on a record.

![image](https://user-images.githubusercontent.com/1459526/88966288-ea6e1e00-d260-11ea-8fad-c4ae5b8a3fff.png)

![image](https://user-images.githubusercontent.com/1459526/88966389-15f10880-d261-11ea-940b-3e9fb316e70c.png)

**Comment by sorenkrabbe** [comment]
Could you please check the browsers console when opening the popout or accessing one of the full pages like the exporter. Additional error details are likely printed there.

**Comment by svinuesa** [comment]
> Could you please check the browsers console when opening the popout or accessing one of the full pages like the exporter. Additional error details are likely printed there.

Hi,
Back from holidays and I am having the same issue.
Here is the error from the console : INVALID_SESSION_ID: Session expired or invalid
    at Object.rest (chrome-extension://aodjmnfhjibkcdimpodiifdjnnncaafh/inspector.js:75:17)
    at async Promise.all (index 2)

**Comment by absuptAlmbrand** [comment]
I have the same problem on all the orgs I have access to. But none of my colleagues does.
I have tried clearing cookies for the site, removing and adding the plugin again.

When I open the plugin pop-out I the the following errors in the console:
inspector.js:63 GET https://dev2.my.salesforce.com/services/data/v48.0/tooling/query?q=select%20QualifiedApiName%2C%20Label%2C%20KeyPrefix%20from%20EntityDefinition%20where%20QualifiedApiName%20%3C%20%27M%27%20limit%202000&cache=0.13787743535161812 401 (Unauthorized)
(anonymous) @ inspector.js:63
rest @ inspector.js:48
getEntityDefinitions @ popup.js:288
loadSobjects @ popup.js:312
componentDidMount @ popup.js:180
e.notifyAll @ react-dom.min.js:12
close @ react-dom.min.js:14
closeAll @ react-dom.min.js:15
perform @ react-dom.min.js:15
s @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
_renderNewRootComponent @ react-dom.min.js:14
_renderSubtreeIntoContainer @ react-dom.min.js:14
render @ react-dom.min.js:14
(anonymous) @ popup.js:26
Promise.then (async)
init @ popup.js:24
initResponseHandler @ popup.js:12
popup.js:297 list entity definitions:  where QualifiedApiName < 'M' limit 2000 SalesforceRestError: INVALID_SESSION_ID: Session expired or invalid
    at Object.rest (chrome-extension://aodjmnfhjibkcdimpodiifdjnnncaafh/inspector.js:75:17)
    at async Promise.all (index 2)
(anonymous) @ popup.js:297
Promise.catch (async)
getEntityDefinitions @ popup.js:296
loadSobjects @ popup.js:312
componentDidMount @ popup.js:180
e.notifyAll @ react-dom.min.js:12
close @ react-dom.min.js:14
closeAll @ react-dom.min.js:15
perform @ react-dom.min.js:15
s @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
_renderNewRootComponent @ react-dom.min.js:14
_renderSubtreeIntoContainer @ react-dom.min.js:14
render @ react-dom.min.js:14
(anonymous) @ popup.js:26
Promise.then (async)
init @ popup.js:24
initResponseHandler @ popup.js:12
inspector.js:63 GET https://dev2.my.salesforce.com/services/data/v48.0/tooling/sobjects/?cache=0.854415016297136 401 (Unauthorized)
(anonymous) @ inspector.js:63
rest @ inspector.js:48
getObjects @ popup.js:277
loadSobjects @ popup.js:305
componentDidMount @ popup.js:180
e.notifyAll @ react-dom.min.js:12
close @ react-dom.min.js:14
closeAll @ react-dom.min.js:15
perform @ react-dom.min.js:15
s @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
_renderNewRootComponent @ react-dom.min.js:14
_renderSubtreeIntoContainer @ react-dom.min.js:14
render @ react-dom.min.js:14
(anonymous) @ popup.js:26
Promise.then (async)
init @ popup.js:24
initResponseHandler @ popup.js:12
popup.js:282 list toolingApi sobjects SalesforceRestError: INVALID_SESSION_ID: Session expired or invalid
    at Object.rest (chrome-extension://aodjmnfhjibkcdimpodiifdjnnncaafh/inspector.js:75:17)
    at async Promise.all (index 1)
(anonymous) @ popup.js:282
Promise.catch (async)
getObjects @ popup.js:281
loadSobjects @ popup.js:305
componentDidMount @ popup.js:180
e.notifyAll @ react-dom.min.js:12
close @ react-dom.min.js:14
closeAll @ react-dom.min.js:15
perform @ react-dom.min.js:15
s @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
_renderNewRootComponent @ react-dom.min.js:14
_renderSubtreeIntoContainer @ react-dom.min.js:14
render @ react-dom.min.js:14
(anonymous) @ popup.js:26
Promise.then (async)
init @ popup.js:24
initResponseHandler @ popup.js:12
inspector.js:63 GET https://dev2.my.salesforce.com/services/data/v48.0/sobjects/?cache=0.21938964262474503 401 (Unauthorized)
(anonymous) @ inspector.js:63
rest @ inspector.js:48
getObjects @ popup.js:277
loadSobjects @ popup.js:303
componentDidMount @ popup.js:180
e.notifyAll @ react-dom.min.js:12
close @ react-dom.min.js:14
closeAll @ react-dom.min.js:15
perform @ react-dom.min.js:15
s @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
_renderNewRootComponent @ react-dom.min.js:14
_renderSubtreeIntoContainer @ react-dom.min.js:14
render @ react-dom.min.js:14
(anonymous) @ popup.js:26
Promise.then (async)
init @ popup.js:24
initResponseHandler @ popup.js:12
popup.js:282 list regularApi sobjects SalesforceRestError: INVALID_SESSION_ID: Session expired or invalid
    at Object.rest (chrome-extension://aodjmnfhjibkcdimpodiifdjnnncaafh/inspector.js:75:17)
    at async Promise.all (index 0)
(anonymous) @ popup.js:282
Promise.catch (async)
getObjects @ popup.js:281
loadSobjects @ popup.js:303
componentDidMount @ popup.js:180
e.notifyAll @ react-dom.min.js:12
close @ react-dom.min.js:14
closeAll @ react-dom.min.js:15
perform @ react-dom.min.js:15
s @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
_renderNewRootComponent @ react-dom.min.js:14
_renderSubtreeIntoContainer @ react-dom.min.js:14
render @ react-dom.min.js:14
(anonymous) @ popup.js:26
Promise.then (async)
init @ popup.js:24
initResponseHandler @ popup.js:12
inspector.js:63 GET https://dev2.my.salesforce.com/services/data/v48.0/tooling/query?q=select%20QualifiedApiName%2C%20Label%2C%20KeyPrefix%20from%20EntityDefinition%20where%20QualifiedApiName%20%3E%3D%20%27M%27%20limit%202000&cache=0.7803131631589526 401 (Unauthorized)
(anonymous) @ inspector.js:63
rest @ inspector.js:48
getEntityDefinitions @ popup.js:288
loadSobjects @ popup.js:313
componentDidMount @ popup.js:180
e.notifyAll @ react-dom.min.js:12
close @ react-dom.min.js:14
closeAll @ react-dom.min.js:15
perform @ react-dom.min.js:15
s @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
_renderNewRootComponent @ react-dom.min.js:14
_renderSubtreeIntoContainer @ react-dom.min.js:14
render @ react-dom.min.js:14
(anonymous) @ popup.js:26
Promise.then (async)
init @ popup.js:24
initResponseHandler @ popup.js:12
popup.js:297 list entity definitions:  where QualifiedApiName >= 'M' limit 2000 SalesforceRestError: INVALID_SESSION_ID: Session expired or invalid
    at Object.rest (chrome-extension://aodjmnfhjibkcdimpodiifdjnnncaafh/inspector.js:75:17)
    at async Promise.all (index 3)

When I open the Data Export page I get the following error in the console:
spinFor SalesforceSoapError: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session hash: OTfhjeloDhCr4WxPGOLMdVB6CR+iumTCb1QbW1qyyGI=
This error usually occurs after a session expires or a user logs out. Decoder: DataInDbSessionKeyDecoder
    at Object.soap (chrome-extension://aodjmnfhjibkcdimpodiifdjnnncaafh/inspector.js:154:17)

I have access to the same orgs through citrix and here the plugin works.

**Comment by TheRealDeShan** [comment]
Hi!

I have the same issue with chrome, if I use firefox the extenstion gets access. So I have a workaround but just a hassle to change browser. The weird thing is that its working on another org on another SF instance but not this one.

This is the error I recieve in chrome:
![error in console](https://user-images.githubusercontent.com/45820672/90498976-3ec23a80-e149-11ea-831a-2d1a8ae047b1.JPG)

Hope the error image helps.

By the way, awesome extension. It's makes my job so much faster. Big thanks

**Comment by meircarlos** [comment]
Hey!

So I was having this same issue and just figured out that it's due to activating My Domain.

The good news is that I just found a solution! Just delete the cookies, login again and you should be good to go! 😄

It seems that the extension got stuck with the cookie of the previous domain, as if it happens to you as it happened to me, then on the error image you sent you can see your old domain and not the new one.

Almost a year late but hopefully it helps!
