### ISSUE TITLE
Update Firefox version

### ISSUE THREAD

**Issue by salejos** [sorenkrabbe/Chrome-Salesforce-inspector#195]
Hi,

Could be possible to update the Firefox version of this great plugin?

Thanks a lot for this usuful plugin!

**Comment by jesperkristensen** [comment]
I have uploaded a new version to addons.mozilla.org. It will be available when Mozilla has reviewed it.

**Comment by enkodellc** [comment]
@jesperkristensen  did you have a commit to this repo for the changes?

**Comment by jesperkristensen** [comment]
I uploaded the latest master branch at 5e780f58d88f3864b4a27374082ceb8d3d38869d
