### ISSUE TITLE
Doesn't work with enhanced domain

### ISSUE THREAD

**Issue by xaifer90** [sorenkrabbe/Chrome-Salesforce-inspector#222]
Hi,
the tool doesn't work in sandbox with enhanced domain activated.

New sandbox urls are basedomain.sandbox.my.salesforce.com

https://help.salesforce.com/s/articleView?id=sf.domain_name_enhanced.htm&type=5

Thanks

**Comment by felix-clay** [comment]
I am also facing this same issue, works in older orgs but doesn't work with new naming convention of sandboxes

**Comment by HerrX2000** [comment]
Also does not work on Firefox.

**Comment by snafuy** [comment]
Workaround: manually add ".sandbox" to the host query string.

**Comment by xaifer90** [comment]
> I am also facing this same issue, works in older orgs but doesn't work with new naming convention of sandboxes

I solved cleaning the cache.
