### ISSUE TITLE
Feature Request: Skip All Button

### ISSUE THREAD

**Issue by Kowalski00** [sorenkrabbe/Chrome-Salesforce-inspector#240]
I've been using import/export a lot between org's to get data to test, fix bugs, develop... and I always try to get as many fields as possible from objects to get consistent data, with the QA org, to reproduce a bug and fix it. But frequently, I need to skip a lot fields and was wondering if it was possible to add a button to skip all invalid fields.

![image](https://user-images.githubusercontent.com/34189031/202198837-efee36b5-297e-41cd-bca0-5de954d75708.png)

**Comment by tprouvot** [comment]
Hi @Kowalski00 you have this functionality available in this fork
https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/pull/234

You can clone the repo locally and install the extension from chrome extension by enabling developer mode

**Comment by Kowalski00** [comment]
Hello, thank you and sorry, i didn't see that it was already a PR and that it was approved.

**Comment by Kowalski00** [comment]
Hello, thank you and sorry, i didn't see that it was already a PR and that it was approved.
