### ISSUE TITLE
Firefox help

### ISSUE THREAD

**Issue by ribena75** [sorenkrabbe/Chrome-Salesforce-inspector#254]
Hi, I have the Firefox extension installed but it appears greyed out in the extensions list, and nothing shows when logged into Salesforce. I do not have any other Salesforce related extensions installed.

**Comment by tprouvot** [comment]
Hi @ribena75 ,
Have you tried using this version ?

https://addons.mozilla.org/en-CA/firefox/addon/salesforce-inspector-reloaded/

**Comment by ribena75** [comment]
Merci
