### ISSUE TITLE
ctrl+space not working

### ISSUE THREAD

**Issue by tage01** [sorenkrabbe/Chrome-Salesforce-inspector#259]
Ctrl+Space doesn't seem to work anymore on the export page when typing a query
Chrome 114.0.5735.134
No other process is using the keyboard shortcut either

**Comment by tprouvot** [comment]
Hi @tage01, 
Seems pretty weird, the extension was not updated since December.
You can try if you have the same behaviour with the new version of the extension ?
https://chrome.google.com/webstore/detail/salesforce-inspector-relo/hpijlohoihegkfehhibggnkbjhoemldh

**Comment by tage01** [comment]
same thing on the new version. i'm guessing it is in fact something on my side hogging the shortcut :/
is there a chance for adding the option to customize the shortcut in the future versions?

**Comment by tprouvot** [comment]
> same thing on the new version. i'm guessing it is in fact something on my side hogging the shortcut :/
> is there a chance for adding the option to customize the shortcut in the future versions?

Why not, it can be a good Idea. Could you create the feature request on the new repo ?

**Comment by tage01** [comment]
sorry, i don't really know how to do so

**Comment by tage01** [comment]
i did however find what was hogging the shortcut. kind of. PowerToys has a feature using **Alt**+Spacebar and this somehow prevented the Ctrl+Space in the Inspector from working.
