### ISSUE TITLE
Inspector Field Access Different Between Browsers

### ISSUE THREAD

**Issue by GoliathMrk1** [sorenkrabbe/Chrome-Salesforce-inspector#270]
Hi Team,

First, Amazing Tool! Its been one of the must haves for working with Salesforce, Awesome Job!

Apologies this is the first time I'm reporting a bug so please let me know if I'm going about it incorrectly? 

The Issue:
I'm Experiencing an issue when querying export data for a specific field, 
On EDGE I cannot see the field ('Uuid') and can't export data for it, but on Mozilla Firefox I can see and export data for the same field.

I do have access to the field and logging into both browsers with the same creds

Info:
EDGE
![image](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/57407027/f9802553-2573-4b12-918d-6274b1c33d86)

![image](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/57407027/d93bfa45-805d-4978-86db-7748dae6eb3b)

FireFox
![image](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/57407027/48ac74c5-93a4-4494-8124-15ac58072d39)

![image](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/57407027/63c70aff-d8ee-4c97-a82e-b153d6ecf7d5)

**Comment by tprouvot** [comment]
Hi @GoliathMrk1 ,
It seems that you are using an old version of the plugin ([1.11](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/blob/master/CHANGES.md)) which was based on Salesforce API version 48.0

<img width="757" alt="image" src="https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/35368290/93ab09bc-1029-4645-b31e-9395a76862bc">
The latest version (1.14) uses the API 56 so if you update the plugin it should solve the issue.

That being said, if you want to use objects and fields delivered post API 56 (Winter 23 I think) you won't be able to do so.
You can use a [new extension based on this one](https://chromewebstore.google.com/detail/salesforce-inspector-relo/hpijlohoihegkfehhibggnkbjhoemldh) which is up to date with latest API version.

**Comment by tprouvot** [comment]
According to the [documentation](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_asset.htm) UUID field was released on version 49

<img width="872" alt="image" src="https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/35368290/d512c9e3-5b93-4882-8a55-3bc2f331e3bb">

**Comment by GoliathMrk1** [comment]
On Edge the Latest version is 1.11

How do i upgrade to a newer version? 

![image](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/57407027/41fc46cf-b933-40d1-9f20-9b038dfb6350)

**Comment by tprouvot** [comment]
Go to the chrome web store where you can install chrome extensions on edge

[Reloaded](https://chromewebstore.google.com/detail/salesforce-inspector-relo/hpijlohoihegkfehhibggnkbjhoemldh)
[OG version](https://chromewebstore.google.com/detail/salesforce-inspector/aodjmnfhjibkcdimpodiifdjnnncaafh)

![image](https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/assets/35368290/48f9c722-90e6-4641-aeb4-7803e231c960)

**Comment by GoliathMrk1** [comment]
Thank you for the assist. the reloaded version is working for the required field.
