### ISSUE TITLE
How to comment code

### ISSUE THREAD

**Issue by s1vsilva** [sorenkrabbe/Chrome-Salesforce-inspector#273]
Dear all, what is the command to comment out a line of code?
I've used --, // /**/ , and none of them work.

**Comment by tprouvot** [comment]
Hi @s1vsilva 
May I asked why are you asking this question here ?
Are you trying to comment a line of code of this extension ?

**Comment by s1vsilva** [comment]
Hi @tprouvot 
No, let me try to explain better
I'm doing some research using “Data Export”.
And for this, I put conditions like Where, and, or... etc.
And to help me, I'd like to comment out some conditions instead of deleting them, since it's exploratory. And I can't, because the SQL code doesn't accept comments.
ex

Select id from leads
where id = '123456'
-- and email = 'ssilva@email.com' (here is an example of what I want to do, but (--) it doesn't work)
and phone = '123456789'

just as an example.

**Comment by tprouvot** [comment]
Comments in data export page are not supported in inspector

**Comment by dufoli** [comment]
hello, 

Comments is supported in Salesforce Inspector Advanced chrome extension.
It is an alternative to original Salesforce Inspector and Salesforce Inspector Reloaded.

You can find it in chrome web store : https://chromewebstore.google.com/detail/salesforce-inspector-adva/dbfimaflmomgldabcphgolbeoamjogji

Comments will be saved in template but will be removed before sending requestion to Salesforce.
We support both // and /* */ comments

Source is available on github if you prefer directly to use last version.
https://github.com/dufoli/Salesforce-Inspector-Advanced

**Comment by s1vsilva** [comment]
@dufoli , great!

Thanks a lot for information.

its worked!
