### ISSUE TITLE
Reverted version number change

### ISSUE THREAD

**Issue by jesperkristensen** [sorenkrabbe/Chrome-Salesforce-inspector#35]
I had to revert a change in 9885d99 since otherwise chrome would refuse to load the addon with an error message saying the version number was malformed.

**Comment by sorenkrabbe** [comment]
The chrome CI build will replace  with the version number in /version.json. This was to allow synced version numbers across browsers

I see the issue when you want to run the chrome plugin directly from source. CI build script should be updated to allow a version number in  addon/manifest.json

**Comment by jesperkristensen** [comment]
I think this is fixed?
