### ISSUE TITLE
Show description column in field overview

### ISSUE THREAD

**Issue by sorenkrabbe** [sorenkrabbe/Chrome-Salesforce-inspector#6]
In the field overview window, a column with the field description should be added.

Note that the description fields is not readily available via the APIs you could expect.

**Comment by sorenkrabbe** [comment]
Currently (API 32) Description field is only available via the Retrieve --> download ZIP API call. I.e. major effort for minor feature

The idea to make the Description field available in other metadata APIs is here: https://success.salesforce.com/ideaView?id=08730000000gO3LAAU

**Comment by jesperkristensen** [comment]
It seems to be possible with the Tooling API (which requires "View Setup and Configuration"):

select QualifiedApiName, Metadata from FieldDefinition where EntityDefinitionId = 'Account'

**Comment by jesperkristensen** [comment]
Removed per issue #39

**Comment by jesperkristensen** [comment]
It is possible to get the field description using the Tooling API, but you have to query one field at a time, or else you get an error like this:

[{"message":"When retrieving results with Metadata or FullName fields, the query qualificatio​ns must specify no more than one row for retrieval. Result size: 356","errorCode":"MALFORMED_QUERY"}]
