### ISSUE TITLE
Inspector Buttons greyed out on Visualforce pages not using the "id" parameter name

### ISSUE THREAD

**Issue by Fabuless** [sorenkrabbe/Chrome-Salesforce-inspector#75]
Opening incidents from within the Remedyforce console, the "show field metadata" and "show all data" buttons are grayed out.  It uses the bmcservicedesk.na9.visual.force.com site.  Entering the ID and pressing the "go" button works as does the "Data Export".  Looking at the same incident via the "recent items" opens the incident outside the Remedyforce console and the inspector fields are available.  This uses the na9.salesforce.com site.  

I previously only had access through the Remedyforce console and the inspector fields worked just fine.  A couple of months ago, I received access through Salesforce (i.e. non Remedyforce) and that's when the inspector buttons were no longer available in Remedyforce.

For us, cases are in Salesforce while incidents are in Remedyforce.  Most users have one or the other, but not both.

The workaround is to open it twice.  First, the search bar opens it through the Remedyforce console and then once the recent items link is created,  the link opens it the second time outside the Remedyforce console.

Is there a way to re-enable it for the Remedyforce console?

![inspector buttons grayed out](https://cloud.githubusercontent.com/assets/21316063/18060987/8bc9d98a-6de6-11e6-8fe2-be423bd61ad5.PNG)

**Comment by jesperkristensen** [comment]
Hi. The inspector looks at the URL in the address bar for a record ID to know which record you are looking at. It can recognize the address format used by Salesforce classic, Lightning Experience/Salesforce1 and Visualforce. If Remedyforce addresses follows one of these formats, then the inspector can recognize it. If Remedyforce has its own address format, we can add support for it in the inspector. Can you give me an example of a Remedyforce address?

**Comment by Fabuless** [comment]
Not sure my reply made it through so I'll repost it:

Here’s the Remedyforce URL:
https://bmcservicedesk.na9.visual.force.com/apex/RemedyforceConsole?record_id=a37E0000000DV1c&objectName=Incident__c&inctype=Incident#false

Here’s the Salesforce URL:
https://na9.salesforce.com/a37E0000000DV1c

**Comment by jesperkristensen** [comment]
Ok, I see why it is not working. It is a Visualforce page, but it is using "record_id" as the parameter name instead of the standard "id" name. Should be easy to fix. I will put it on my todo list.

**Comment by Fabuless** [comment]
Oh yeah.  Wonder why they changed it.

 

If I change it back to the standard “id” in the address bar, the Inspector has the buttons enabled and I can see “all data”.  Obviously the webpage no longer displays correctly but at least accounting for a different parameter format does indeed appear to fix it.

 

Thanks!

**Comment by jesperkristensen** [comment]
I have fixed it so it should now work with Remedyforce. It should be in the next release. I plan to make at least one release per Salesforce release.
