### ISSUE TITLE
HTTP error 401 Unauthorized message:"Session expired or invalid" errorCode:"INVALID_SESSION_ID" when mydomain is enabled

### ISSUE THREAD

**Issue by gambacloud** [sorenkrabbe/Chrome-Salesforce-inspector#98]
Hi,

We've enabled mydomain in our SB and get **Error describing global: HTTP error 401 Unauthorized [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]** when trying to view data etc.

I tried to update the URL manually without luck:
Original: chrome-extension://aodjmnfhjibkcdimpodii++++ncaafh/inspect.html?host=cs81.salesforce.com&q=a0326000001y++++

Any workaround?

Cheers,

**Comment by jesperkristensen** [comment]
Did you just enable My Domain and then it stopped working? Or has it never worked in your org?

What is your My Domain settings?

It works for me with these settings:
Prevent login from https://login.salesforce.com : Unchecked
Redirect Policy: Redirected to the same page within the domain

Are you using some custom authentication?
Which browser?

**Comment by gambacloud** [comment]
Hi @jesperkristensen  many thanks for the prompt reply. We've just enabled myDomain and in the extension url page it was still referring to the "old" url. 

For some reason it started to work correctly this morning... 
So .. Much Ado About Nothing :)

Cheers

**Comment by bbuck-enernoc** [comment]
Same experience here. We enabled mydomain in sandbox and received this error for a couple of days. Then it stopped and salesforce inspector works now even with mydomain enabled. Sorry, don't know exactly how long.
